In [1]:
# Import necessary libraries
import numpy as np
import pandas as pd

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

# Load the Wine Quality Red dataset
df = pd.read_csv("winequality-red.csv",delimiter=';')

# Separate features and target
X = df.iloc[:,:-1].values
y = df.iloc[:,-1].values

# Split the dataset into an 80-20 training-test set
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

# Create an instance of the StandardScaler class
sc = StandardScaler()

# Fit the StandardScaler on the features from the training set and transform it
X_train[:,:] = sc.fit_transform(X_train[:,:])

# Apply the transform to the test set
X_test[:,:] = sc.transform(X_test[:,:])

# Print the scaled training and test datasets
X_train = np.round(X_train, 5)
X_test = np.round(X_test, 5)

print(X_train)
print(X_test)

[[ 0.21833  0.88971  0.19209 ...  1.0935   0.45822  1.12318]
 [-1.29017 -1.78878  0.65275 ... -0.40044 -0.4012   1.40827]
 [ 1.49475 -0.78435  1.01105 ... -0.07567  0.51552 -0.58739]
 ...
 [-0.65196  0.4991  -1.08752 ...  1.28836 -0.68767 -0.87248]
 [-0.24582 -1.84458  0.39683 ...  0.05424  0.80199  1.40827]
 [-1.46422 -1.34237 -0.06383 ...  0.50892 -0.68767  2.92878]]
[[-3.61860e-01  1.64290e-01 -9.85150e-01 ... -4.65390e-01 -1.30000e-04
  -7.77450e-01]
 [-3.03840e-01 -1.70530e-01 -5.24490e-01 ...  5.08920e-01 -1.03144e+00
  -8.72480e-01]
 [ 1.37871e+00  7.78110e-01 -2.68570e-01 ... -2.05580e-01  1.83329e+00
  -4.92360e-01]
 ...
 [-1.37400e-02  3.87490e-01 -1.15020e-01 ... -1.04998e+00 -7.44960e-01
  -5.87390e-01]
 [ 2.76350e-01 -1.45397e+00  6.01570e-01 ... -1.04998e+00  1.71750e-01
   7.43050e-01]
 [ 4.50410e-01  1.30823e+00 -1.18989e+00 ... -1.40620e-01 -6.87670e-01
  -6.82420e-01]]
